[package]
name = "section4"
version = "0.1.0"
authors = ["Azu0925 <yamaneko564783@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
